config/routes.rb
Rails.application.routes.draw do
  
  
  resources :iceriks
  devise_for :users
  
  resources :posts do 
    resources :comments
  end

  
  root 'home#index'
  get 'home/nasil_uye_olunur'
  get 'home/iade_sartlari'
  get 'home/kullanim_kosullari'
  get 'home/kuponlari_nasil_gorurum'
  get 'home/gizlilik'
  get 'home/yasal_uyari'
  get 'home/sss'
  get 'home/hakkimizda'
  get 'home/iletisim'
  get 'home/mac_sonuclari'
  get 'home/bakiye_yukle'
  get 'home/canli_destek'
  get 'home/para_cek'
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :post
    belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :destroy]
  
  # GET /comments
  # GET /comments.json
  def index
    @comments = @post.comments.all
    
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = @post.comments.find(params[:id])
  end
  

  # GET /comments/new
  def new
    @comment = @post.comments.new
  end

  # POST /comments
  # POST /comments.json
  def create
      @post=Post.find(params[:post_id])
      @comment = @post.comments.build(comment_params)  
      @comment.user=current_user
      @macsayisi=Comment.where(post_id: params[:post_id]).count  
      if @comment.sum==nil
         @comment.sum=1
         @comment.save
      end
        
    respond_to do |format|
      if @comment.save
          
          (0..@macsayisi).each do |i|
             @sum = Comment.where(post_id: params[:post_id]).last.sum  * Comment.where(post_id: params[:post_id]).pluck(*:oran)[i].to_f 
             @comment.sum=@sum
             @comment.save
          end

        
        format.js
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
     
  end

              
             
  def destroy
    @comment = @post.comments.find(params[:id])
    @o=@comment.oran.to_f
    @comment.destroy
    
    @p=@comment.sum.to_f
    @n=Comment.where(post_id: params[:post_id]).last.sum.to_f / @o
    
    @r=Comment.where(post_id: params[:post_id]).last
    @r.sum=@n
    @r.save
    
    respond_to do |format|
      format.js
      format.html { redirect_to post_url(params[:post_id]) }
    end
  end

  private
    def set_comment
      @post = Post.find(params[:post_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:bdy,:mac,:mbs,:kod,:oran,:durum,:sum)
    end
    
    

  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/create.js.erb
$('#comments').append('<li class="list-group-item"><span class="glyphicon glyphicon-ok"></span>&emsp;<a href="/posts/<%=@post.id %>/comments/<%=@comment.id %>" data-method="delete" rel="nofollow" data-confirm="Maçı Silmek istiyormusunuz?" remote= "true"><span  class="glyphicon glyphicon-trash"></span></a>&emsp;<b> <%=@comment.bdy%> </b> &emsp;<b class="btn-danger btn-xs"><%=@comment.kod%></b><br><b><%=@comment.mac%></b><br><b>MS : <%=@comment.durum%></b>&emsp;<b class="btn-primary btn-xs"><%=@comment.mbs%></b>&emsp;<b>Oran : <%=@comment.oran%></b><br><br><b>Toplam Oran : <%=@comment.sum.round(2)%></b> </li>').slideDown();

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Bdy</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.bdy %></td>
        <td><%= comment.mac %></td>
        <td><%= comment.mbs %></td>
        <td><%= comment.kod %></td>
        <td><%= comment.oran %></td>
        <td><%= comment.durum %></td>

        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bdy:</strong>
  <%= @comment.bdy %>
  <%= @comment.mac %>
  <%= @comment.mbs %>
  <%= @comment.kod %>
  <%= @comment.oran %>
  <%= @comment.durum %>

</p>