config/routes.rb
Rails.application.routes.draw do
  
  
  resources :iceriks
  devise_for :users
  
  resources :posts do 
    resources :comments
  end

  
  root 'home#index'
  get 'home/nasil_uye_olunur'
  get 'home/iade_sartlari'
  get 'home/kullanim_kosullari'
  get 'home/kuponlari_nasil_gorurum'
  get 'home/gizlilik'
  get 'home/yasal_uyari'
  get 'home/sss'
  get 'home/hakkimizda'
  get 'home/iletisim'
  get 'home/mac_sonuclari'
  get 'home/bakiye_yukle'
  get 'home/canli_destek'
  get 'home/para_cek'
  

end

app/models/icerik.rb
class Icerik < ActiveRecord::Base
end

app/controllers/iceriks_controller.rb
class IceriksController < ApplicationController
  before_action :set_icerik, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new,:show, :edit, :destroy,:index]
  before_action :kontrol, only:[:edit, :destroy,:show,:index]
  
  def kontrol
    if current_user.email!='admin@admin.com'
      redirect_to posts_path
    end  
  end
  # GET /iceriks
  # GET /iceriks.json
  def index
    @iceriks = Icerik.all
  end

  # GET /iceriks/1
  # GET /iceriks/1.json
  def show
  end

  # GET /iceriks/new
  def new
    @icerik = Icerik.new
  end

  # GET /iceriks/1/edit
  def edit
  end

  # POST /iceriks
  # POST /iceriks.json
  def create
    @icerik = Icerik.new(icerik_params)

    respond_to do |format|
      if @icerik.save
        format.html { redirect_to @icerik, notice: 'Icerik was successfully created.' }
        format.json { render :show, status: :created, location: @icerik }
      else
        format.html { render :new }
        format.json { render json: @icerik.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /iceriks/1
  # PATCH/PUT /iceriks/1.json
  def update
    respond_to do |format|
      if @icerik.update(icerik_params)
        format.html { redirect_to @icerik, notice: 'Icerik was successfully updated.' }
        format.json { render :show, status: :ok, location: @icerik }
      else
        format.html { render :edit }
        format.json { render json: @icerik.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /iceriks/1
  # DELETE /iceriks/1.json
  def destroy
    @icerik.destroy
    respond_to do |format|
      format.html { redirect_to iceriks_url, notice: 'Icerik was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_icerik
      @icerik = Icerik.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def icerik_params
      params.require(:icerik).permit(:tarih, :mbs, :saat, :lig, :kod, :mac, :oran1, :oran2, :oran3, :oran4, :oran5, :oran6, :oran7, :oran8, :oran9, :oran10, :oran11, :oran12, :oran13, :oran14, :oran15, :oran16, :oran17, :oran18, :oran19, :oran20)
    end
end

app/helpers/iceriks_helper.rb
module IceriksHelper
end

app/views/iceriks/_form.html.erb
<div class="section nomargin notopborder nobg">
<%= form_for(@icerik) do |f| %>
  <% if @icerik.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@icerik.errors.count, "error") %> prohibited this icerik from being saved:</h2>

      <ul>
      <% @icerik.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tarih %><br>
    <%= f.text_field :tarih %>
  </div>
  <div class="field">
    <%= f.label :mbs %><br>
    <%= f.text_field :mbs %>
  </div>
  <div class="field">
    <%= f.label :saat %><br>
    <%= f.text_field :saat %>
  </div>
  <div class="field">
    <%= f.label :lig %><br>
    <%= f.text_field :lig %>
  </div>
  <div class="field">
    <%= f.label :kod %><br>
    <%= f.text_field :kod %>
  </div>
  <div class="field">
    <%= f.label :mac %><br>
    <%= f.text_field :mac %>
  </div>
  <div class="field">
     <th>1</th>
    <%= f.text_field :oran1 %>
  </div>
  <div class="field">
    <th>X</th>
    <%= f.text_field :oran2 %>
  </div>
  <div class="field">
    <th>2</th>
    <%= f.text_field :oran3 %>
  </div>
  <div class="field">
    <th>1-X</th>
    <%= f.text_field :oran4 %>
  </div>
  <div class="field">
    <th>1-2</th>
    <%= f.text_field :oran5 %>
  </div>
  <div class="field">
     <th>X-2</th>
    <%= f.text_field :oran6 %>
  </div>
  <div class="field">
    <th>İY 1,5A</th>
    <%= f.text_field :oran7 %>
  </div>
  <div class="field">
    <th>İY 1,5Ü</th>
    <%= f.text_field :oran8 %>
  </div>
  <div class="field">
    <th>1,5 A</th>
    <%= f.text_field :oran9 %>
  </div>
  <div class="field">
    <th>1,5 Ü</th>
    <%= f.text_field :oran10 %>
  </div>
  <div class="field">
   <th>2,5 A</th>
    <%= f.text_field :oran11 %>
  </div>
  <div class="field">
    <th>2,5 Ü</th>
    <%= f.text_field :oran12 %>
  </div>
  <div class="field">
    <th>3,5 A</th>
    <%= f.text_field :oran13 %>
  </div>
  <div class="field">
    <th>3,5 Ü</th>
    <%= f.text_field :oran14 %>
  </div>
  <div class="field">
    <th>VAR</th>
    <%= f.text_field :oran15 %>
  </div>
  <div class="field">
    <th>YOK</th>
    <%= f.text_field :oran16 %>
  </div>
  <div class="field">
    <th>0-1TG</th>
    <%= f.text_field :oran17 %>
  </div>
  <div class="field">
    <th>2-3TG</th>
    <%= f.text_field :oran18 %>
  </div>
  <div class="field">
    <th>4-6TG</th>
    <%= f.text_field :oran19 %>
  </div>
  <div class="field">
    <th>+7 TG</th>
    <%= f.text_field :oran20 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/iceriks/edit.html.erb
<div class="section nomargin notopborder nobg">
<h1>Editing Icerik</h1>

<%= render 'form' %>

<%= link_to 'Show', @icerik %> |
<%= link_to 'Back', iceriks_path %>
</div>

app/views/iceriks/index.html.erb
<div class="section nomargin notopborder nobg">
<p id="notice"><%= notice %></p>

<h1>Listing Iceriks</h1>

<table>
  <thead>
    <tr>
      <th>tarih</th>
      <th>Mbs</th>
      <th>Saat</th>
      <th>Lig</th>
      <th>Kod</th>
      <th>Mac</th>
      <th>1</th>
      <th>X</th>
      <th>2</th>
      <th>1-X</th>
      <th>1-2</th>
      <th>X-2</th>
      <th>İY 1,5A</th>
      <th>İY 1,5Ü</th>
      <th>1,5 A</th>
      <th>1,5 Ü</th>
      <th>2,5 A</th>
      <th>2,5 Ü</th>
      <th>3,5 A</th>
      <th>3,5 Ü</th>
      <th>VAR</th>
      <th>YOK</th>
      <th>0-1TG</th>
      <th>2-3TG</th>
      <th>4-6TG</th>
      <th>+7 TG</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @iceriks.each do |icerik| %>
      <tr>
        <td><%= icerik.tarih %></td>
        <td><%= icerik.mbs %></td>
        <td><%= icerik.saat %></td>
        <td><%= icerik.lig %></td>
        <td><%= icerik.kod %></td>
        <td><%= icerik.mac %></td>
        <td><%= icerik.oran1 %></td>
        <td><%= icerik.oran2 %></td>
        <td><%= icerik.oran3 %></td>
        <td><%= icerik.oran4 %></td>
        <td><%= icerik.oran5 %></td>
        <td><%= icerik.oran6 %></td>
        <td><%= icerik.oran7 %></td>
        <td><%= icerik.oran8 %></td>
        <td><%= icerik.oran9 %></td>
        <td><%= icerik.oran10 %></td>
        <td><%= icerik.oran11 %></td>
        <td><%= icerik.oran12 %></td>
        <td><%= icerik.oran13 %></td>
        <td><%= icerik.oran14 %></td>
        <td><%= icerik.oran15 %></td>
        <td><%= icerik.oran16 %></td>
        <td><%= icerik.oran17 %></td>
        <td><%= icerik.oran18 %></td>
        <td><%= icerik.oran19 %></td>
        <td><%= icerik.oran20 %></td>
        <td><%= link_to 'Show', icerik %></td>
        <td><%= link_to 'Edit', edit_icerik_path(icerik) %></td>
        <td><%= link_to 'Destroy', icerik, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Icerik', new_icerik_path %>
</div>

app/views/iceriks/new.html.erb
<div class="section nomargin notopborder nobg">
<h1>New Icerik</h1>

<%= render 'form' %>

<%= link_to 'Back', iceriks_path %>
</div>

app/views/iceriks/show.html.erb
<div class="section nomargin notopborder nobg">
<p id="notice"><%= notice %></p>

<p>
  <strong>Mbs:</strong>
  <%= @icerik.tarih %>
</p>

<p>
  <strong>Mbs:</strong>
  <%= @icerik.mbs %>
</p>

<p>
  <strong>Saat:</strong>
  <%= @icerik.saat %>
</p>

<p>
  <strong>Lig:</strong>
  <%= @icerik.lig %>
</p>

<p>
  <strong>Kod:</strong>
  <%= @icerik.kod %>
</p>

<p>
  <strong>Mac:</strong>
  <%= @icerik.mac %>
</p>

<p>
  <strong>Oran1:</strong>
  <%= @icerik.oran1 %>
</p>

<p>
  <strong>Oran2:</strong>
  <%= @icerik.oran2 %>
</p>

<p>
  <strong>Oran3:</strong>
  <%= @icerik.oran3 %>
</p>

<p>
  <strong>Oran4:</strong>
  <%= @icerik.oran4 %>
</p>

<p>
  <strong>Oran5:</strong>
  <%= @icerik.oran5 %>
</p>

<p>
  <strong>Oran6:</strong>
  <%= @icerik.oran6 %>
</p>

<p>
  <strong>Oran7:</strong>
  <%= @icerik.oran7 %>
</p>

<p>
  <strong>Oran8:</strong>
  <%= @icerik.oran8 %>
</p>

<p>
  <strong>Oran9:</strong>
  <%= @icerik.oran9 %>
</p>

<p>
  <strong>Oran10:</strong>
  <%= @icerik.oran10 %>
</p>

<p>
  <strong>Oran11:</strong>
  <%= @icerik.oran11 %>
</p>

<p>
  <strong>Oran12:</strong>
  <%= @icerik.oran12 %>
</p>

<p>
  <strong>Oran13:</strong>
  <%= @icerik.oran13 %>
</p>

<p>
  <strong>Oran14:</strong>
  <%= @icerik.oran14 %>
</p>

<p>
  <strong>Oran15:</strong>
  <%= @icerik.oran15 %>
</p>

<p>
  <strong>Oran16:</strong>
  <%= @icerik.oran16 %>
</p>

<p>
  <strong>Oran17:</strong>
  <%= @icerik.oran17 %>
</p>

<p>
  <strong>Oran18:</strong>
  <%= @icerik.oran18 %>
</p>

<p>
  <strong>Oran19:</strong>
  <%= @icerik.oran19 %>
</p>

<p>
  <strong>Oran20:</strong>
  <%= @icerik.oran20 %>
</p>

<%= link_to 'Edit', edit_icerik_path(@icerik) %> |
<%= link_to 'Back', iceriks_path %>
</div>